# PPS Device (captured via pps_capture in kernel)
refclock PPS /dev/pps0 poll 3 precision 1e-9 refid PPS filter 16 minsamples 16 prefer

# GPS Serial (NMEA) via UART for cuau0
refclock SOCK /var/run/chrony.clk.cuau0.sock poll 3 refid GPS0 delay 0.5 offset 0.250

# GPS Serial (NMEA) via UART for cuau1
refclock SOCK /var/run/chrony.clk.cuau1.sock poll 3 refid GPS1 delay 0.5 offset 0.250



# Performance & Precision
makestep 0.1 3
lock_all


# Monitoring & Maintenance
log refclocks
logdir /var/log/chrony
driftfile /var/db/chrony/drift
ntsdumpdir /var/db/chrony


# Handle Leap Seconds
leapsectz right/UTC


# Fallback Servers
pool stratipi.pool.ntp.org iburst minpoll 8 maxpoll 10


# NTP SERVER
allow 0.0.0.0/0
