hostname="stratipi"

# IPv4 Configuration
ifconfig_DEFAULT="DHCP"
defaultroute_delay="0"

# IPv6 Configuration
ifconfig_DEFAULT_ipv6="inet6 accept_rtadv"
ipv6_activate_all_interfaces="YES"
defaultroute_ipv6_delay="0"
rtsold_enable="YES"
rtsold_flags="-a"


# Default Services
ldconfig_enable="YES"
sshd_enable="YES"
zfs_enable="YES"


# Entirely disable moused
moused_enable="NO"
moused_nondefault_enable="NO"


# TTY Screen Configs
allscreens_flags="-s 8"
allscreens_kbdflags="-b quiet.off"
keyrate="fast"


# Start logging GPS data
gpsd_baud_enable="YES"
gpsd_enable="YES"
gpsd_flags="-n -b /dev/cuau0 /dev/cuau1 /dev/pps0"


# Start NTP service (chrony)
save_time_enable="YES"
chronyd_enable="YES"


# PTP Master for USB Ethernet (ue0 - Raspberry Pi 3)
ptpd2_ue0_enable="YES"
ptpd2_ue0_flags="-c /usr/local/etc/ptpd2_ue0.conf"

# PTP Master for Onboard Ethernet (genet0 - Raspberry Pi 4)
ptpd2_genet0_enable="YES"
ptpd2_genet0_flags="-c /usr/local/etc/ptpd2_genet0.conf"


# Used by CheckMK
inetd_enable="YES"


# LOL mail
sendmail_enable="NONE"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"
