hostname="stratipi"

# PTP Master for USB Ethernet (ue0 - Raspberry Pi 3)
ptpd2_ue0_enable="YES"
ptpd2_ue0_flags="-c /usr/local/etc/ptpd2_ue0.conf"

# PTP Master for Onboard Ethernet (genet0 - Raspberry Pi 4)
ptpd2_genet0_enable="YES"
ptpd2_genet0_flags="-c /usr/local/etc/ptpd2_genet0.conf"
