gpt

# Sizes are in 512-byte sectors (historical reasons)
NANO_MEDIASIZE=15625000 # 8GB
NANO_RAM_TMPVARSIZE=102400 # 50 MiB

# NANO_REVISION="15.1"
# NANO_BRANCH="RELEASE"

# XXXJL pkg: Missing shlib libexecinfo.so.1 required by cmake-core
# XXXJL FreeBSD-kernel-generic -> FreeBSD-kernel-generic-mmccam
NANO_PKGBASE_LIST="FreeBSD-kernel-generic FreeBSD-set-minimal FreeBSD-console-tools FreeBSD-bsdconfig FreeBSD-ssh FreeBSD-pf FreeBSD-ipf FreeBSD-ipfw FreeBSD-libexecinfo"

NANO_CUSTOMIZE="cust_comconsole cust_allow_ssh_root cust_install_files cust_pkgng"

NANO_PACKAGE_DIR=/usr/local/poudriere/data/packages/nanobsd-latest/All
NANO_PACKAGE_LIST="*"

NANO_CFGDIR=/home/jlduran/Developer/nanobsd/stratipi/cfg
NANO_METALOG_CFG=/home/jlduran/Developer/nanobsd/stratipi/cfg.mtree

NANO_CUST_FILESDIR=/home/jlduran/Developer/nanobsd/stratipi/Files
NANO_CUST_FILES_MTREE=/home/jlduran/Developer/nanobsd/stratipi/Files.mtree

# Configure ttys and console devices
cust_comconsole() {
	# Enable getty on console
	sed -i "" -e '/^ttyu[0-3]/s/onifconsole/off/' ${NANO_WORLDDIR}/etc/ttys

	# Set the dashboard terminal
	sed -i "" -e '/^ttyv7/s/getty Pc"\t/getty dashboard"/' ${NANO_WORLDDIR}/etc/ttys

	# Disable unused terminals
	sed -i "" -e 's/^ttyv8/#ttyv8/' ${NANO_WORLDDIR}/etc/ttys
	sed -i "" -e 's/^dcons/#dcons/' ${NANO_WORLDDIR}/etc/ttys
	sed -i "" -e 's/^xc0/#xc0/' ${NANO_WORLDDIR}/etc/ttys
	sed -i "" -e 's/^rcons/#rcons/' ${NANO_WORLDDIR}/etc/ttys

	if $do_precompiled && [ -z "$NANO_NOPKGBASE" ]; then
		tgt_pkg_update_file_sha256 etc/ttys
		tgt_pkg_update_config_files_content etc/ttys
	fi
}

# XXXJL
# Raspberry Pi customizations missing (msdos dir)
