NANO_NAME="stratipi"
NANO_IMG1NAME="${NANO_NAME}.img"

default
NANO_PLAN="default"
NANO_BOARDNAME="RPI"
NANO_DRIVE=sdda0

#NANO_REVISION="15.1"
#NANO_BRANCH="RELEASE"

# Sizes in bytes
NANO_MEDIASIZE="8GB"
NANO_RAM_TMPVARSIZE="100MiB"
NANO_CIDATA_SIZE="500MiB"
NANO_ALIGN="4MiB"

NANO_PKGBASE_LIST="FreeBSD-kernel-generic-mmccam FreeBSD-set-minimal FreeBSD-console-tools FreeBSD-bsdconfig FreeBSD-ssh FreeBSD-pf FreeBSD-ipf FreeBSD-ipfw FreeBSD-libexecinfo"
NANO_LOADER_KERNEL="kernel.GENERIC-MMCCAM"

NANO_CUSTOMIZE="cust_comconsole cust_allow_ssh_root cust_pkgng cust_install_files"

SRC="/home/jlduran/Developer/nanobsd/${NANO_NAME}"

NANO_PACKAGE_LIST=$(awk 'BEGIN {ORS=" "} !/^#/ && NF' ${SRC}/pkglist)
NANO_PACKAGE_LIST="${NANO_PACKAGE_LIST} net/wifi-firmware-mt7601u-kmod"

# /cfg partition files
NANO_CFGDIR="${SRC}/cfg"
NANO_METALOG_CFG="${SRC}/cfg.mtree"

# Override files
NANO_CUST_FILESDIR="${SRC}/Files"
NANO_CUST_FILES_MTREE="${SRC}/Files.mtree"

# MS-DOS/CIDATA files
NANO_CIDATA_FILESDIR="${SRC}/cidata"

# XXXJL Upstream
# Create an MS Basic Data Partition for nuageinit (cidata)
make_cidata_partition() {
	local cidatadir cidata_sects fat_type

	MINCLS16=4085	# minimum FAT16 clusters (0xff5U)
	MINCLS32=65525	# minimum FAT32 clusters (0xfff5U)
	cidata_sects=$(awk -v label="cidata" '$5 == label {print $4}' "${NANO_LOG}/_.partitioning")
	if [ "$cidata_sects" -ge "$MINCLS32" ]; then
		fat_type=32
	elif [ "$cidata_sects" -ge "$MINCLS16" ]; then
		fat_type=16
	else
		fat_type=12
	fi

	cidatadir="${NANO_OBJ}/_.cidata"
	rm -rf "$cidatadir"
	mkdir -p "$cidatadir"

	cp -a "${NANO_CIDATA_FILESDIR}/"* "$cidatadir"

	makefs -t msdos \
	    -o fat_type="16" \
	    -o sectors_per_cluster=1 \
	    -o volume_label="CIDATA" \
	    -o OEM_string="" \
	    -s "${cidata_sects}b" \
	    -T "$NANO_TIMESTAMP" \
	    "${NANO_OBJ}/_.cidata.image" "$cidatadir"

	rm -rf "$cidatadir"
}

last_orders() {
	pprint 2 "Compressing final binary disk image"
	zstd --fast=1 -T0 "${NANO_DISKIMGDIR}/${NANO_IMG1NAME}" -o "${NANO_DISKIMGDIR}/${NANO_IMG1NAME}.zst" --quiet --force --rm
}
