NANO_NAME="stratipi"
NANO_IMG1NAME="${NANO_NAME}.img"

default
NANO_PLAN="default"
NANO_BOARDNAME="RPI"
NANO_DRIVE=sdda0

#NANO_REVISION="15.1"
#NANO_BRANCH="RELEASE"

# Sizes in bytes
NANO_MEDIASIZE="8GB"
NANO_RAM_TMPVARSIZE="100MiB"
NANO_ALIGN="4MiB"

# XXXJL pkg: Missing shlib libexecinfo.so.1 required by cmake-core
# XXXJL FreeBSD-kernel-generic -> FreeBSD-kernel-generic-mmccam
NANO_PKGBASE_LIST="FreeBSD-kernel-generic FreeBSD-set-minimal FreeBSD-console-tools FreeBSD-bsdconfig FreeBSD-ssh FreeBSD-pf FreeBSD-ipf FreeBSD-ipfw FreeBSD-libexecinfo"

NANO_CUSTOMIZE="cust_comconsole cust_allow_ssh_root cust_pkgng cust_install_files"

SRC="/home/jlduran/Developer/nanobsd/${NANO_NAME}"

NANO_PACKAGE_LIST=$(awk 'BEGIN {ORS=" "} !/^#/ && NF' ${SRC}/pkglist)

# /cfg partition files
NANO_CFGDIR="${SRC}/cfg"
NANO_METALOG_CFG="${SRC}/cfg.mtree"

# Override files
NANO_CUST_FILESDIR="${SRC}/Files"
NANO_CUST_FILES_MTREE="${SRC}/Files.mtree"

# XXXJL
# Raspberry Pi customizations missing (msdos dir)

last_orders() {
	pprint 2 "Compressing final binary disk image"
	zstd --fast=1 -T0 "${NANO_DISKIMGDIR}/${NANO_IMG1NAME}" -o "${NANO_DISKIMGDIR}/${NANO_IMG1NAME}.zst" --quiet --force --rm
}
