#!/bin/sh
# PROVIDE: save_time
# REQUIRE: FILESYSTEMS
# BEFORE: chronyd
# KEYWORD: shutdown

. /etc/rc.subr
name="save_time"
rcvar="save_time_enable"

start_cmd="save_time_start"
stop_cmd="save_time_stop"

save_time_start() {
	if [ -f "$last_time_file" ]; then
		echo "Restoring time from ${last_time_file}"
		NEW_TIME=$(/usr/bin/stat -f "%Sm" -t "%Y%m%d%H%M.%S" "$last_time_file")
		/bin/date "${NEW_TIME}"
	fi
}

save_time_stop() {
	echo "Saving current time to ${last_time_file}"
	touch "$last_time_file"
}

load_rc_config $name
run_rc_command "$1"
