#!/bin/sh

CEOL=$(printf '\033[K')

while true; do
	printf "\033[H"
	i=0

	chronyc tracking | cut -c1-38 | while read -r line; do
		[ $i -gt 0 ] && printf "\n"
		printf "%s%s" "$line" "$CEOL"
		i=$((i + 1))
	done

	printf "\033[J"
	sleep 1
done



