#!/bin/sh

TMUX=/usr/local/bin/tmux
SPLIT="$TMUX split-window"
RESIZE="$TMUX resize-pane"
SELECT="$TMUX select-pane"
OPTION="$TMUX set-option"
SESSION="dashboard-$$"

# Create a new tmux session with our current width/height
ROOT=$($TMUX new-session -d -s $SESSION -x 148 -y 39 -P -F "#{pane_id}")
TOP=$ROOT

# Split out bottom pane first to ensure heights work
BOTTOM1=$($TMUX split-window -v -t $ROOT -P -F "#{pane_id}")
$TMUX resize-pane -t $BOTTOM1 -y 10

# Split out the rest of the panes
BOTTOM2=$($TMUX split-window -v -t $BOTTOM1 -P -F "#{pane_id}")
RIGHT1=$($TMUX split-window -h -t $ROOT -P -F "#{pane_id}")
RIGHT2=$($TMUX split-window -v -t $RIGHT1 -P -F "#{pane_id}")
RIGHT3=$($TMUX split-window -h -t $RIGHT2 -P -F "#{pane_id}")
LEFT1=$ROOT
LEFT2=$($TMUX split-window -v -t $LEFT1 -P -F "#{pane_id}")


# Set the width of the two columns
$TMUX resize-pane -t $LEFT1  -x 67
$TMUX resize-pane -t $RIGHT1 -x 80

# Set "chrony" sizes
$TMUX resize-pane -t $RIGHT2 -x 40 -y 13

# Set the logo height
$TMUX resize-pane -t $LEFT1 -y 8

# Set "chrony sources / sourcestats" height
$TMUX resize-pane -t $BOTTOM1 -y 8

# Set the status bar height
$TMUX resize-pane -t $BOTTOM2 -y 1




# Quick helper function for setting BG/FG colors
colors() {
	$SELECT -t "$1" -P "bg=$2,fg=$3"
}

colors $LEFT1	black blue
colors $LEFT2	black white
colors $RIGHT1	black white
colors $RIGHT2	black white
colors $BOTTOM1	black white
colors $BOTTOM2	black white

# Make borders suck less
$OPTION -t $SESSION pane-border-style "bg=black,fg=grey"
$OPTION -t $SESSION pane-active-border-style "bg=black,fg=grey"

# Lockdown, no user input
#$TMUX unbind-key -a -t $SESSION
$OPTION -t $SESSION key-table off
$OPTION -t $SESSION mouse off
$OPTION -t $SESSION status off

# Slight delay to ensure all TTY settings sync before launching apps
BARRIER=$($TMUX split-window -v -t "$ROOT" -P -F "#{pane_id}" "true")
$TMUX kill-pane -t "$BARRIER"

# Quick helper function to launch commands in each tmux pane
guard() {
	$TMUX respawn-pane -t "$1" -k "exec /sbin/dash-guard $2"
}

# Launch all the things!!!
guard $LEFT1	"/sbin/strati-logo"
guard $LEFT2	"/usr/local/bin/tty-clock -sc -C 6 -f '%A, %B %d, %Y' -d 0 -a 25000000"
guard $RIGHT1	"/usr/local/bin/cgps -s"
guard $RIGHT2	"/sbin/dash-tracking"
guard $RIGHT3	"/sbin/dash-clients"
guard $BOTTOM1	"/sbin/dash-chrony"
guard $BOTTOM2	"/sbin/statusbar"


# Attach
$TMUX -u -2 attach-session -t $SESSION -r
