#!/bin/sh

# ANSI codes
RST="\033[0m"
INV="\033[46;30m"
TXT="\033[36m"
TTL="\033[94m"
ERR="\033[31m"
CLR="\033[K"
ALT="${INV}ALT${RST}"
VRT="\342\224\202"

# Restore cursor on exit or Ctrl+C
trap 'printf "\033[?25h"; exit' 0 1 2 15

# Hide cursor
printf "\033[?25l"


while true; do
	# Get the NIC IPv4 address
	IP=$(ifconfig -u | awk '
		/^[a-z0-9]/ { ip = ""; active = 0 }
		$1 == "inet" && $2 !~ /^127\./ { ip = $2 }
		/status: (active|associated)/ { active = 1 }
		ip && active { print ip; exit }
	')

	if [ -z "$IP" ]; then
		IP="${ERR}offline"
	fi

	LOAD=$(sysctl -n vm.loadavg | tr -d '{}' | xargs)
	TEMP=$(sysctl -n dev.cpu.0.temperature)

	ZPOOL=$(
		zpool list | tail -n 1 |
		awk -v t="$TXT" -v r="$RST" '{print t $3 r "/" t $2 r}'
	)

	# Print status line
	printf "\t%b  $VRT  %b  $VRT  %b  $VRT  %b  $VRT  %b  $VRT  %b${CLR}\r" \
		"${TTL}Terminal${RST} ${ALT}+${INV}F1${RST} - ${ALT}+${INV}F7${RST}" \
		"${TTL}Status${RST} ${ALT}+${INV}F8${RST}" \
		"${TTL}Load${RST} ${TXT}$LOAD${RST}" \
		"${TTL}Temp${RST} ${TXT}$TEMP${RST}" \
		"${TTL}ZFS${RST} $ZPOOL" \
		"${TTL}IP${RST} ${TXT}$IP${RST}"

	sleep 1
done
