#!/bin/sh
#
# Copyright (c) 2026 [XXX]
#
# SPDX-License-Identifier: BSD-2-Clause
#

set -e

. /etc/nanobsd.conf

: "${NANO_ROOT:?NANO_ROOT not set in /etc/nanobsd.conf}"
: "${NANO_ALTROOT:?NANO_ALTROOT not set in /etc/nanobsd.conf}"

root_mountfrom=$(kenv vfs.root.mountfrom)
root_mountfrom=${root_mountfrom#*:}

case "$root_mountfrom" in
"/dev/gpt/${NANO_ALTROOT}")
	echo "Updating '${NANO_ROOT}'..."
	exec sh /usr/local/sbin/updatep1
	;;
"/dev/gpt/${NANO_ROOT}")
	echo "Updating '${NANO_ALTROOT}'..."
	exec sh /usr/local/sbin/updatep2
	;;
*)
	echo "Invalid root device '${root_mountfrom}'." >&2
	exit 1
	;;
esac
