[ptpengine]
interface = genet0
preset = masteronly
transport = ipv4
ip_mode = multicast
priority1 = 0
priority2 = 0
domain = 0

[clock]
no_adjust = Y

[global]
; Unique files for this instance
lock_file = /var/run/ptpd2_genet0.pid
status_file = /var/run/ptpd2_genet0.status
