#!/bin/sh

CEOL=$(printf '\033[K')

while true; do
	printf "\033[H"

	CLIENTS=$(chronyc -cn clients | grep -vE '^(127\.0\.0\.1|::1)' | grep -c '')

	(
	echo "Clients: $CLIENTS,Pkts,Last"
	chronyc clients | awk 'NR>2 && $1 !~ /^=/ {
		val=$6; num=val; sub(/[y|d|h|m|s]$/,"",num);
		unit=substr(val,length(val));

		if (val == "-") { s=999999999 }
		else if (unit == "y") { s=num*31536000 }
		else if (unit == "d") { s=num*86400 }
		else if (unit == "h") { s=num*3600 }
		else if (unit == "m") { s=num*60 }
		else { s=num }
		print $1, $2, $6, s

	}' | sort -h -k4,4n | head -n 12 | awk '{print $1 "," $2 "," $3}'
	) | column -s, -t | sed "s/$/$CEOL/" | printf "%s" "$(cat)"

	printf "\033[J"
	sleep 1
done
