#!/bin/sh

DELAY=1

if [ $# -eq 0 ]; then
	echo "Usage: $0 <command> [args...]"
	exit 1
fi

while true; do
	"$@"

	EXIT_CODE=$?
	echo "--- Process exited with code $EXIT_CODE. Restarting in ${DELAY}s... ---"

	sleep "$DELAY"
done
